
# Baseimage specially for raspberry pi usage
#FROM resin/rpi-raspbian:jessie
#VOLUME /tmp
# Installing openjdk-8-headless like in the standard Docker container
#RUN apt-get update && apt-get install -y \
#      openjdk-8-jre-headless
FROM openjdk:8-jdk-stretch
VOLUME /tmp
ARG JAVA_OPTS
ENV JAVA_OPTS=$JAVA_OPTS
ADD target/discovery-server-0.0.1-SNAPSHOT.jar discovery-server.jar
EXPOSE 8761
#ENTRYPOINT exec java $JAVA_OPTS -jar discovery-server.jar
# For Spring-Boot project, use the entrypoint below to reduce Tomcat startup time.
ENTRYPOINT exec java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar discovery-server.jar
